apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: veteranfinder

resources:
  - namespace.yaml
  - configmaps.yaml
  - api-deployment.yaml
  - web-deployment.yaml
  - ingress.yaml
  - hpa-pdb.yaml

commonLabels:
  app.kubernetes.io/part-of: veteranfinder
  app.kubernetes.io/managed-by: kustomize
